spring.application.name=user-service
spring.data.mongodb.uri=${MONGO_URI}

spring.data.mongodb.database=22kd1a0548

jwt.secret=YmFzZTY0LWVuY29kZWQtc2VjcmV0LWtleS1mb3ItanNvbg==
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

